table Benchmark
	lineageTag: 561b4883-8a58-42fb-bac4-f1027ed79c03

	column country_code
		dataType: string
		lineageTag: 57a03f33-b99b-42f2-a6af-72cba9f0a83f
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column country_name
		dataType: string
		lineageTag: a77d7e57-beae-4e2b-b524-8192de833fe5
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 562f4bfb-ae02-4f14-aaf5-ec02636233a2
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column metric_code
		dataType: string
		lineageTag: 48ab81c9-652c-45d9-bff3-ec7186f23d98
		summarizeBy: none
		sourceColumn: metric_code

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		lineageTag: 24348667-99c2-4e44-b7a3-f34c8a9d73f7
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	partition Benchmark = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\fact_benchmark.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"country_code", type text}, {"country_name", type text}, {"year", Int64.Type}, {"metric_code", type text}, {"value", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

