table Region
	lineageTag: 507dd043-fe37-42fd-9f16-fe9d1ab01e79

	column region_code
		dataType: int64
		formatString: 0
		lineageTag: 10230ef0-8d82-45b1-9941-58e6d45445e0
		summarizeBy: none
		sourceColumn: region_code

		annotation SummarizationSetBy = Automatic

	column region_name
		dataType: string
		lineageTag: ed782511-0ad2-45eb-ae28-f81d84f69f5f
		summarizeBy: none
		sourceColumn: region_name

		annotation SummarizationSetBy = Automatic

	column is_national
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 642503b5-5632-45a1-8f35-74c7fafa3fe7
		summarizeBy: none
		sourceColumn: is_national

		annotation SummarizationSetBy = Automatic

	column region_type
		dataType: string
		lineageTag: fa3e052c-862c-42a1-bea7-aac80b66c7d0
		summarizeBy: none
		sourceColumn: region_type

		annotation SummarizationSetBy = Automatic

	column region_short
		dataType: string
		lineageTag: 11a33015-0b01-471b-b5ba-2c1d29cd843a
		summarizeBy: none
		sourceColumn: region_short

		annotation SummarizationSetBy = Automatic

	partition Region = m
		mode: import
		source =
				let
				     Source = Csv.Document(
				      File.Contents(DataFolder & "\dim_region.csv"),
				      [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				  ),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"region_code", Int64.Type}, {"region_name", type text}, {"is_national", type logical}, {"region_type", type text}, {"region_short", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

