table SectorContributions
	lineageTag: 81ede6f2-acff-4bab-ace5-af8f96de9c5a

	column year
		dataType: int64
		formatString: 0
		lineageTag: 9e95867a-e847-485a-a587-826476e5fd69
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column total_growth_pct
		dataType: double
		lineageTag: 44429091-dbb4-469a-921c-441e7b56e114
		summarizeBy: none
		sourceColumn: total_growth_pct

		annotation SummarizationSetBy = Automatic

	column shares_reliable
		dataType: boolean
		lineageTag: 3e543945-5686-4ff2-a45c-c583d12e13c3
		summarizeBy: none
		sourceColumn: shares_reliable

		annotation SummarizationSetBy = Automatic

	column sector
		dataType: string
		lineageTag: 07ded623-e82b-402a-b08f-ae2fd1f39852
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column contribution_pp
		dataType: double
		lineageTag: f3183761-2251-442a-b859-3d754eb843b5
		summarizeBy: none
		sourceColumn: contribution_pp

		annotation SummarizationSetBy = Automatic

	partition SectorContributions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\fact_sector_contributions.csv"), [Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"year", Int64.Type}, {"Agriculture", type number}, {"Industry", type number}, {"Services", type number}, {"total_growth_pct", type number}, {"shares_reliable", type logical}}),
				    #"Unpivoted" = Table.UnpivotOtherColumns(#"Changed Type", {"year", "total_growth_pct", "shares_reliable"}, "sector", "contribution_pp")
				in
				    #"Unpivoted"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

